USE praticingschema;
CREATE TABLE FIRSTTABLE (
  STAFF_ID VARCHAR(20) PRIMARY KEY,
  STAFF_NAME VARCHAR(30) NOT NULL,
  AGE INT,
  DEPARTMENT VARCHAR(50),
  COURSE VARCHAR(50)
);

SELECT * FROM FIRSTTABLE;

 FIRSTTABLE INSERT INTO FIRSTTABLE (STAFF_ID, STAFF_NAME, AGE, DEPARTMENT, COURSE) VALUES 
('1', 'SCPETEE', '18', 'MECHATRONICS' , 'ENGINE');
COMMIT;
INSERT INTO FIRSTTABLE (STAFF_ID, STAFF_NAME, AGE, DEPARTMENT, COURSE) VALUES 
('2', 'YIBARI', '28', 'MECHA' , 'ENGINED');
